### PR TITLE
Update rk_serial.c

### PR DESCRIPTION
**Pull request by DwaineGarden**
English Translations on Coding Comments

### CODE REVIEW

**Comment by DwaineGarden** [comment]
Also fixed the merged 1.1.6 rds Makefile description.

**Comment by jamesgol** [comment]
I was considering doing this and never got around to it, but I would keep the Chinese in as well so on the off chance that Newsmy/Bonovo opens up the code base it would work well for everyone.

**Comment by DwaineGarden** [comment]
Ok...

**Comment by DwaineGarden** [comment]
Can you just pull the rds comment one.   Just fixes the wrong reference to canbus in the rds makefile.

**Comment by jamesgol** [comment]
The Makefile change?  That appears to have already been merged a while ago, I suspect your branch is not current

**Comment by Zaphod-Beeblebrox** [comment]
These are getting pulled to the wrong branch as well.
we are on Master, not kitkat, right?

**Comment by DwaineGarden** [comment]
I thought we were supposed to create pull request to KitKat. And it would get added to master later on?
On May 14, 2015 11:19 AM, Mike Wilson notifications@github.com wrote:These are getting pulled to the wrong branch as well.
we are on Master, not kitkat, right?

**Pull request closed without merging**
